const attrs = [
        'onAnimationEnd',
        'onAnimationIteration',
        'onAnimationStart',
        'onBlur',
        'onCanPlay',
        'onCanPlayThrough',
        'onChange',
        'onClick',
        'onComplete',
        'onContextMenu',
        'onCopy',
        'onCut',
        'onDblClick',
        'onDrag',
        'onDragEnd',
        'onDragEnter',
        'onDragLeave',
        'onDragOver',
        'onDragStart',
        'onDrop',
        'onDurationChange',
        'onEmptied',
        'onEnded',
        'onError',
        'onFocus',
        'onInput',
        'onKeyDown',
        'onKeyPress',
        'onKeyUp',
        'onLoad',
        'onLoadedData',
        'onLoadedMetadata',
        'onLoadStart',
        'onMouseDown',
        'onMouseEnter',
        'onMouseLeave',
        'onMouseMove',
        'onMouseOut',
        'onMouseOver',
        'onMouseUp',
        'onPaste',
        'onPause',
        'onPlay',
        'onPlaying',
        'onProgress',
        'onRateChange',
        'onScroll',
        'onSeeked',
        'onSeeking',
        'onSelect',
        'onStalled',
        'onSubmit',
        'onSuspend',
        'onTimeUpdate',
        'onTouchCancel',
        'onTouchEnd',
        'onTouchMove',
        'onTouchStart',
        'onTransitionEnd',
        'onVolumeChange',
        'onWaiting',
        'onWheel'
    ],
    attrsToEvents = {};

for(let i = 0; i < attrs.length; i++) {
    attrsToEvents[attrs[i]] = attrs[i].substr(2).toLowerCase();
}

export default attrsToEvents;
