var expect = require('expect.js');
require('./renderToDom/renderToDom.spec.js');
require('./renderToString/renderToString.spec.js');
require('./patch/patch.spec.js');
require('./patchDom/patchDom.spec.js');
require('./adoptDom/adoptDom.spec.js');
require('./mountToDom/mountToDom.spec.js');
require('./unmountFromDom/unmountFromDom.spec.js');
require('./domEvents/domEvents.spec.js');
require('./component/component.spec.js');
